name: Python Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.2.0
      with:
        mysql-version: '8.0'
        root-password: 'pasword.'
        database: 'gestion_mantenciones'

    - name: Run linting with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Run tests
      env:
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASSWORD: pasword
        DB_NAME: gestion_mantenciones
      run: |
        pip install pytest
        pytest

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: .pytest_cache/
